// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylwajcnexpjwohmjeopj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2FqY25leHBqd29obWplb3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTU5NjIsImV4cCI6MjA2NTU3MTk2Mn0.7Z26fbIPIH5FajW-Uy72EPwpT2tcTetKwiLM4u-0VnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);